name: Deploy React to Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      USERNAME: ${{ secrets.USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build
        continue-on-error: false

      - name: SSH into Instance and Prepare Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            echo "🔄 Removing old build files..."
            sudo -n rm -rf /var/www/react-app/*
            echo "✅ Old files removed."
          
      - name: Upload Build Files to Instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: "build/*"
          target: "/var/www/react-app"

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.INSTANCE_IP }}
          username: ${{ env.USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            echo "🔄 Restarting Nginx..."
            sudo -n systemctl restart nginx
            echo "✅ Deployment complete!"